name: Remove Test Code on PR to Main

# 触发条件：当有PR指向main分支时
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  remove-test-code:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # 要获取所有历史以便能推送更改
          fetch-depth: 0
          # 检出PR的分支
          ref: ${{ github.head_ref }}
          
      - name: Remove test code
        run: |
          rm -rf Vendor/bin/ \
                 Vendor/myclabs/ \
                 Vendor/nikic/ \
                 Vendor/phar-io/ \
                 Vendor/phpunit/ \
                 Vendor/sebastian/ \
                 Vendor/staabm/ \
                 Vendor/theseer/
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          # 只有当有更改时才提交
          if git diff --staged --quiet; then
            echo "No test code to remove"
          else
            git commit -m "Auto-remove test code [skip ci]"
            git push
          fi
        env:
          # 使用GitHub提供的token进行推送
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
